version: '3'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - PG_USERNAME=postgres
      - PG_PASSWORD=postgres
  backend:
    build:
      context: backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - db
  frontend:
    build:
      context: frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 8080:8080